### ISSUE TITLE
Error: cannot access '.../SCRATCH-1D_1.1/tmp/20190602-010133-829841579409/dataset.pro': No such file or directory

### ISSUE THREAD

**Issue by johnnytam100** [sameerkhurana10/DSOL_rv0.2#2]
Hi! I am trying to use your DeepSol neural network to predict the solubility of the designs.

Unfortunately, I am stuck at the test run as stated in README.md. My command and the error are as follow:

> (dsol) cltam@cltam-System-Product-Name:~/Desktop/deepsol_trial$ R --vanilla < /home/cltam/Desktop/DSOL_rv0.2-v0.3/sameerkhurana10-DSOL_rv0.2-20562ad/scripts/PaRSnIP.R seq1-8_DPBB_trimmed.fasta /home/cltam/SCRATCH-1D_1.1/bin/run_SCRATCH-1D_predictors.sh newtest 32
> 
> ...
> 
> [SCRATCH-1D_predictions.pl] 1 protein sequence(s) found
> [SCRATCH-1D_predictions.pl] generating sequence profiles...
> chmod: cannot access '/home/cltam/SCRATCH-1D_1.1/tmp/20190602-010133-829841579409/dataset.pro': No such file or directory
> [SCRATCH-1D_predictions.pl] failed generating sequence profiles...
> [1] 1
> Error in file(file, "r") : cannot open the connection
> Calls: PaRSnIP ... PaRSnIP.calc.features.test -> as.vector -> read.fasta -> scan -> file
> In addition: Warning message:
> In file(file, "r") :
>   cannot open file '/tmp/RtmpQsM2Kr/tmp3a395e10ade.ss': No such file or directory
> Execution halted

I have googled a similar error message but didn't help.

May I have your suggestion on how to deal with the error?

Thanks!

**Comment by raghvendra5688** [comment]
Hi.

This is a common problem with SCRATCH on certain operating systems. There are two ways to work around this. 
1. You can try to install the latest SCRATCH i.e. SCRATCH-1D_1.2 and try again to generate features
2. You can go to: a) https://machinelearning-protein.qcri.org/index.html
                            b) Register as new user
                            c) Activate your account
                            d) Once you login, you can go to Run and click on DeepSol
                            e) Now you can run your job for DeepSol with the option 1 for DeepSol S1, 2 for DeepSol S2 and 3 for DeepSol S3.

Regards,
Raghvendra

**Comment by johnnytam100** [comment]
Hi Raghvendra,

Thanks for your suggestion of upgrading to  SCRATCH-1D_1.2, the error message for SCRATCH disappeared.

Unfortunately, I still have one more error message afterward, which reads

> [1] 1
> Error in file(file, "r") : cannot open the connection
> Calls: PaRSnIP ... PaRSnIP.calc.features.test -> as.vector -> read.fasta -> scan -> file
> In addition: Warning message:
> In file(file, "r") :
>   cannot open file '/tmp/RtmpEhjbNM/tmp335b6ad45028.ss': No such file or directory
> Execution halted

Do you have any suggestion for this error message?

I will try the web sever of DeepSol too.

Thanks!

**Comment by BILLBEATTHEPEAT** [comment]
> Hi Raghvendra,
> 
> Thanks for your suggestion of upgrading to SCRATCH-1D_1.2, the error message for SCRATCH disappeared.
> 
> Unfortunately, I still have one more error message afterward, which reads
> 
> > [1] 1
> > Error in file(file, "r") : cannot open the connection
> > Calls: PaRSnIP ... PaRSnIP.calc.features.test -> as.vector -> read.fasta -> scan -> file
> > In addition: Warning message:
> > In file(file, "r") :
> > cannot open file '/tmp/RtmpEhjbNM/tmp335b6ad45028.ss': No such file or directory
> > Execution halted
> 
> Do you have any suggestion for this error message?
> 
> I will try the web sever of DeepSol too.
> 
> Thanks!

I also have this trouble. Did you figure out with it?

**Comment by raghvendra5688** [comment]
Hi Billbeatthepeat,

This is something which is happening due to SCRATCH on some Unix platforms and I don't think we can do anything about it.

With Regards,
Raghvendra

**Comment by shoz** [comment]
I guess this problem is because the BLAST executable under the SCRATCH directory([SCRATCH]/pkg/blast-2.2.26) is not based on x86. I downloaded the appropriate BLAST binary from the NCBI server(ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.26/) and replaced it, and it worked.

**Comment by amani-acog** [comment]
The documentation shows we can carryout the process as parallelised process by enabling number of cores to be used. But after fixing the issue with SCRATCH and BLAST, I am able to run the process without any interruptions but I could not carry out the parallel processing even after mentioning the cores.
