### ISSUE TITLE
How to explain the results

### ISSUE THREAD

**Issue by werhoog** [sameerkhurana10/DSOL_rv0.2#5]
Predicted_Class	P0	P1
1	0.496959	0.503788
0	0.641231	0.359205
1	0.483336	0.51587

Hi, thanks for this software. Could you help me explain this result(shown already). I guess the P0 represents the probability of label 0. If so, how I can read the first column (1-0-1). Does the rank of 1-0-1 represent the rank of the amino acid sequences in the input fasta file?  

Also, do you have any suggestion if the input protein has many chains and each chain has the same amino acid sequence as other chains?

**Comment by raghvendra5688** [comment]
Hi,

The first column represents the predicted label for the entire protein i.e. 1 for soluble protein and 0 for insoluble protein. 

You can have any protein as input as long as the length of the protein sequence is less than 1000 amino acids.
